### ISSUE TITLE
I want display mac local dictionary result, do you have any idea?

### ISSUE THREAD

**Issue by fucusy** [mofus/Alfred-Google-Translate#6]
I want display mac local dictionary result, do you have any idea?

**Comment by mofus** [comment]
no sorry, this is something completely different than what this extension does.
have you tried the command "spell" in alfred?

**Comment by fucusy** [comment]
oh, Thank you ! it is what I need.

**Comment by mofus** [comment]
Great to hear. I will close this issue now.
